/*
 * generated by Xtext
 */
package eu.supersede.dynadapt.dsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import eu.supersede.dynadapt.dsl.ui.internal.AspectActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AspectExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return AspectActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return AspectActivator.getInstance().getInjector(AspectActivator.EU_SUPERSEDE_DYNADAPT_DSL_ASPECT);
	}
	
}
