/*
 * generated by Xtext
 */
package eu.supersede.dynadapt.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AspectUiModule extends eu.supersede.dynadapt.dsl.ui.AbstractAspectUiModule {
	public AspectUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
