/*
 * generated by Xtext
 */
package cz.zcu.yafmt.clang.bcl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import cz.zcu.yafmt.clang.bcl.ui.internal.BooleanConstraintLanguageActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BooleanConstraintLanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return BooleanConstraintLanguageActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return BooleanConstraintLanguageActivator.getInstance().getInjector(BooleanConstraintLanguageActivator.CZ_ZCU_YAFMT_CLANG_BCL_BOOLEANCONSTRAINTLANGUAGE);
	}
	
}
