/*
 * generated by Xtext
 */
package eu.supersede.dynadapt.dsl;

import org.eclipse.xtext.scoping.IGlobalScopeProvider;
import org.eclipse.xtext.scoping.IScopeProvider;
import org.eclipse.xtext.serializer.tokens.SerializerScopeProviderBinding;

import com.google.inject.Binder;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AspectRuntimeModule extends eu.supersede.dynadapt.dsl.AbstractAspectRuntimeModule {
//	@Override
//	public Class<? extends IGlobalScopeProvider> bindIGlobalScopeProvider() {
//		return GMLImportUriGlobalScopeProvider.class;
//	}
//	
//	@Override
//	public Class<? extends XtextResourceSet> bindXtextResourceSet() {
//		return ARTISTResourceSet.class;
//	}
	
//	@Override
//	public Class<? extends Manager> bindIContainer$Manager() {
//		return super.bindIContainer$Manager();
//	}
//	
//	@Override
//	public Class<? extends Provider> bindIAllContainersState$Provider() {
//		return super.bindIAllContainersState$Provider();
//	}
	
//	@Override
//	public Class<? extends IValueConverterService> bindIValueConverterService() {
//		return ARTISTCommonConverters.class;
//	}
	
//	@Override
//	public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
//		return ARTISTQualifiedNameProvider.class;
//	}
	
	@Override
	public Class<? extends IGlobalScopeProvider> bindIGlobalScopeProvider() {
		return AspectImportUriGlobalScopeProvider.class;
	}
	
	@Override
	public void configureSerializerIScopeProvider(Binder binder) {
		binder.bind(IScopeProvider.class).annotatedWith(SerializerScopeProviderBinding.class).to(bindIScopeProvider());
	}
	
//	@Override
//	public Class<? extends ILinkingService> bindILinkingService() {
//		return ARTISTLinkingService.class;
//	}
//	
//	@Override
//	public Class<? extends ILinker> bindILinker() {
//		return super.bindILinker();
//	}
	
//	@Override
//	public Class<? extends IGlobalScopeProvider> bindIGlobalScopeProvider() {
//		return ImportUriGlobalScopeProvider.class;
//	}
}
