/*
 * generated by Xtext 2.9.1
 */
package eu.supersede.dynadapt.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class AspectStandaloneSetup extends AspectStandaloneSetupGenerated {

	def static void doSetup() {
		new AspectStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
