/*
 * generated by Xtext
 */
package eu.supersede.dynadapt.dsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class AspectStandaloneSetup extends AspectStandaloneSetupGenerated{

	public static void doSetup() {
		new AspectStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

