/*
* generated by Xtext
*/
package cz.zcu.yafmt.clang.bcl.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import cz.zcu.yafmt.clang.bcl.services.BooleanConstraintLanguageGrammarAccess;

public class BooleanConstraintLanguageParser extends AbstractContentAssistParser {
	
	@Inject
	private BooleanConstraintLanguageGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected cz.zcu.yafmt.clang.bcl.ui.contentassist.antlr.internal.InternalBooleanConstraintLanguageParser createParser() {
		cz.zcu.yafmt.clang.bcl.ui.contentassist.antlr.internal.InternalBooleanConstraintLanguageParser result = new cz.zcu.yafmt.clang.bcl.ui.contentassist.antlr.internal.InternalBooleanConstraintLanguageParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getContextualExpressionAccess().getAlternatives(), "rule__ContextualExpression__Alternatives");
					put(grammarAccess.getNegationAccess().getAlternatives(), "rule__Negation__Alternatives");
					put(grammarAccess.getPrimaryExpressionAccess().getAlternatives(), "rule__PrimaryExpression__Alternatives");
					put(grammarAccess.getContextualExpressionAccess().getGroup_0(), "rule__ContextualExpression__Group_0__0");
					put(grammarAccess.getContextualExpressionAccess().getGroup_1(), "rule__ContextualExpression__Group_1__0");
					put(grammarAccess.getEquationAccess().getGroup(), "rule__Equation__Group__0");
					put(grammarAccess.getEquationAccess().getGroup_1(), "rule__Equation__Group_1__0");
					put(grammarAccess.getImplicationAccess().getGroup(), "rule__Implication__Group__0");
					put(grammarAccess.getImplicationAccess().getGroup_1(), "rule__Implication__Group_1__0");
					put(grammarAccess.getDisjunctionAccess().getGroup(), "rule__Disjunction__Group__0");
					put(grammarAccess.getDisjunctionAccess().getGroup_1(), "rule__Disjunction__Group_1__0");
					put(grammarAccess.getConjunctionAccess().getGroup(), "rule__Conjunction__Group__0");
					put(grammarAccess.getConjunctionAccess().getGroup_1(), "rule__Conjunction__Group_1__0");
					put(grammarAccess.getNegationAccess().getGroup_1(), "rule__Negation__Group_1__0");
					put(grammarAccess.getPrimaryExpressionAccess().getGroup_0(), "rule__PrimaryExpression__Group_0__0");
					put(grammarAccess.getPrimaryExpressionAccess().getGroup_1(), "rule__PrimaryExpression__Group_1__0");
					put(grammarAccess.getContextualExpressionAccess().getContextIdAssignment_0_2(), "rule__ContextualExpression__ContextIdAssignment_0_2");
					put(grammarAccess.getContextualExpressionAccess().getExpressionAssignment_0_4(), "rule__ContextualExpression__ExpressionAssignment_0_4");
					put(grammarAccess.getContextualExpressionAccess().getContextIdAssignment_1_2(), "rule__ContextualExpression__ContextIdAssignment_1_2");
					put(grammarAccess.getContextualExpressionAccess().getExpressionAssignment_1_4(), "rule__ContextualExpression__ExpressionAssignment_1_4");
					put(grammarAccess.getEquationAccess().getRightPartAssignment_1_2(), "rule__Equation__RightPartAssignment_1_2");
					put(grammarAccess.getImplicationAccess().getRightPartAssignment_1_2(), "rule__Implication__RightPartAssignment_1_2");
					put(grammarAccess.getDisjunctionAccess().getRightPartAssignment_1_2(), "rule__Disjunction__RightPartAssignment_1_2");
					put(grammarAccess.getConjunctionAccess().getRightPartAssignment_1_2(), "rule__Conjunction__RightPartAssignment_1_2");
					put(grammarAccess.getNegationAccess().getExpressionAssignment_1_2(), "rule__Negation__ExpressionAssignment_1_2");
					put(grammarAccess.getPrimaryExpressionAccess().getFeatureIdAssignment_0_1(), "rule__PrimaryExpression__FeatureIdAssignment_0_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			cz.zcu.yafmt.clang.bcl.ui.contentassist.antlr.internal.InternalBooleanConstraintLanguageParser typedParser = (cz.zcu.yafmt.clang.bcl.ui.contentassist.antlr.internal.InternalBooleanConstraintLanguageParser) parser;
			typedParser.entryRuleExpression();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public BooleanConstraintLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(BooleanConstraintLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
