import java.util.ArrayList;
import java.util.List;

import org.eclipse.core.resources.IFolder;
import org.eclipse.core.resources.ResourcesPlugin;
import org.eclipse.core.runtime.Platform;
import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.mwe.utils.StandaloneSetup;

import cz.zcu.yafmt.model.fm.FeatureModel;
import eu.supersede.dynadapt.aom.dsl.parser.AdaptationParser;
import eu.supersede.dynadapt.aom.dsl.parser.IAdaptationParser;
import eu.supersede.dynadapt.dsl.aspect.Aspect;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'zavala' at '9/23/16 12:26 PM' with Gradle 2.14.1
 *
 * @author zavala, @date 9/23/16 12:26 PM
 */
public class ModelRepository {

	public List<URI> getAspectModelsURIs(String featureSUPERSEDEId) {
		new StandaloneSetup().setPlatformUri("../");
		//IFolder folder = platform. ("platform:/resource/eu.supersede.dynadapt.modelrepository/models/aspects");
		return null;
	}

	public List<Aspect> getAspectModels(String featureSUPERSEDEId) {
		List<Aspect> aspects = new ArrayList<Aspect>();

		IAdaptationParser parser = new AdaptationParser();

		new StandaloneSetup().setPlatformUri("../");

		URI aspectModelURI = URI.createURI(
				"platform:/resource/eu.supersede.dynadapt.modelrepository/models/aspects/googleplayapi/googleplayapi.aspect");

		parser.loadUMLResource(URI.createURI(
				"platform:/resource/eu.supersede.dynadapt.modelrepository/models/advices/GooglePlayAPI.uml"));
		parser.loadProfileResource(URI
				.createURI("platform:/resource/eu.supersede.dynadapt.modelrepository/models/pofiles/adm.profile.uml"));
		parser.loadPatternResource(URI.createURI(
				"platform:/resource/eu.supersede.dynadapt.modelrepository/models/patterns/monitoring_reconfiguration_queries.vql"));
		FeatureModel fm = parser.loadFeatureResource(URI.createURI(
				"platform:/resource/eu.supersede.dynadapt.modelrepository/models/featureconfigmodels/MonitoringSystem.yafm"));

		Aspect adaptation = parser.parseAdaptationModel(aspectModelURI);

		System.out.println(fm);

		System.out.println(adaptation.getFeature().getId());

		// if
		// (adaptation.getFeature().getId().equalsIgnoreCase(featureSUPERSEDEId))
		// aspects.add(adaptation);

		// String featureName = adaptation.getFeature().getName();
		// String patternName =
		// adaptation.getPointcuts().get(0).getPattern().getName();
		return aspects;
	}

	public static void main(String args[]) {
		ModelRepository m = new ModelRepository();
		m.getAspectModels("GooglePlay_API_GooglePlay");
	}
}
