/*
* generated by Xtext
*/
package cz.zcu.yafmt.clang.bcl;

import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.ISetup;
import org.eclipse.emf.ecore.resource.Resource;

import com.google.inject.Guice;
import com.google.inject.Injector;

/**
 * Generated from StandaloneSetup.xpt!
 */
@SuppressWarnings("all")
public class BooleanConstraintLanguageStandaloneSetupGenerated implements ISetup {

	public Injector createInjectorAndDoEMFRegistration() {
		org.eclipse.xtext.common.TerminalsStandaloneSetup.doSetup();

		Injector injector = createInjector();
		register(injector);
		return injector;
	}
	
	public Injector createInjector() {
		return Guice.createInjector(new cz.zcu.yafmt.clang.bcl.BooleanConstraintLanguageRuntimeModule());
	}
	
	public void register(Injector injector) {
	if (!EPackage.Registry.INSTANCE.containsKey("http://zcu.cz/yafmt/clang/bcl")) {
		EPackage.Registry.INSTANCE.put("http://zcu.cz/yafmt/clang/bcl", cz.zcu.yafmt.clang.bcl.model.ModelPackage.eINSTANCE);
	}

	}
}
