/*
* generated by Xtext
*/
package cz.zcu.yafmt.clang.bcl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class BooleanConstraintLanguageAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("cz/zcu/yafmt/clang/bcl/parser/antlr/internal/InternalBooleanConstraintLanguage.tokens");
	}
}
