/*
 * generated by Xtext
 */
package cz.zcu.yafmt.clang.bcl;

import org.eclipse.xtext.parser.antlr.ISyntaxErrorMessageProvider;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class BooleanConstraintLanguageRuntimeModule extends cz.zcu.yafmt.clang.bcl.AbstractBooleanConstraintLanguageRuntimeModule {

    public Class<? extends ISyntaxErrorMessageProvider> bindISyntaxErrorMessageProvider() {
        return BooleanConstraintLanguageErrorMessageProvider.class;
    }
    
}
