/*
* generated by Xtext
*/
package cz.zcu.yafmt.clang.bcl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import cz.zcu.yafmt.clang.bcl.services.BooleanConstraintLanguageGrammarAccess;

public class BooleanConstraintLanguageParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private BooleanConstraintLanguageGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected cz.zcu.yafmt.clang.bcl.parser.antlr.internal.InternalBooleanConstraintLanguageParser createParser(XtextTokenStream stream) {
		return new cz.zcu.yafmt.clang.bcl.parser.antlr.internal.InternalBooleanConstraintLanguageParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Expression";
	}
	
	public BooleanConstraintLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(BooleanConstraintLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
