/*
 * generated by Xtext
 */
package eu.supersede.dynadapt.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import eu.supersede.dynadapt.dsl.services.AspectGrammarAccess;

public class AspectParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private AspectGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected eu.supersede.dynadapt.dsl.parser.antlr.internal.InternalAspectParser createParser(XtextTokenStream stream) {
		return new eu.supersede.dynadapt.dsl.parser.antlr.internal.InternalAspectParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Aspect";
	}
	
	public AspectGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AspectGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
