/*
 * generated by Xtext
 */
package eu.supersede.dynadapt.dsl.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class AspectGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class AspectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "eu.supersede.dynadapt.dsl.Aspect.Aspect");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAspectKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cFeatureKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cFeatureAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cFeatureFeatureCrossReference_4_0 = (CrossReference)cFeatureAssignment_4.eContents().get(0);
		private final RuleCall cFeatureFeatureQualifiedNameParserRuleCall_4_0_1 = (RuleCall)cFeatureFeatureCrossReference_4_0.eContents().get(1);
		private final Keyword cCommaKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cAdviceKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cAdviceAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final CrossReference cAdviceModelCrossReference_7_0 = (CrossReference)cAdviceAssignment_7.eContents().get(0);
		private final RuleCall cAdviceModelQualifiedNameParserRuleCall_7_0_1 = (RuleCall)cAdviceModelCrossReference_7_0.eContents().get(1);
		private final Keyword cCommaKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cPointcutsKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cLeftCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cPointcutsAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cPointcutsPointcutParserRuleCall_11_0 = (RuleCall)cPointcutsAssignment_11.eContents().get(0);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cCommaKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Assignment cPointcutsAssignment_12_1 = (Assignment)cGroup_12.eContents().get(1);
		private final RuleCall cPointcutsPointcutParserRuleCall_12_1_0 = (RuleCall)cPointcutsAssignment_12_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Keyword cCommaKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Keyword cCompositionsKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Keyword cLeftCurlyBracketKeyword_16 = (Keyword)cGroup.eContents().get(16);
		private final Assignment cCompositionsAssignment_17 = (Assignment)cGroup.eContents().get(17);
		private final RuleCall cCompositionsCompositionParserRuleCall_17_0 = (RuleCall)cCompositionsAssignment_17.eContents().get(0);
		private final Group cGroup_18 = (Group)cGroup.eContents().get(18);
		private final Keyword cCommaKeyword_18_0 = (Keyword)cGroup_18.eContents().get(0);
		private final Assignment cCompositionsAssignment_18_1 = (Assignment)cGroup_18.eContents().get(1);
		private final RuleCall cCompositionsCompositionParserRuleCall_18_1_0 = (RuleCall)cCompositionsAssignment_18_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_19 = (Keyword)cGroup.eContents().get(19);
		private final Keyword cRightCurlyBracketKeyword_20 = (Keyword)cGroup.eContents().get(20);
		
		//Aspect:
		//	"aspect" name=ID "{"
		//	"feature" feature=[fm::Feature|QualifiedName]
		//	"," "advice" advice=[uml::Model|QualifiedName]
		//	"," "pointcuts" "{" pointcuts+=Pointcut ("," pointcuts+=Pointcut)* "}"
		//	"," "compositions" "{" compositions+=Composition ("," compositions+=Composition)* "}"
		//	"}";
		@Override public ParserRule getRule() { return rule; }

		//"aspect" name=ID "{" "feature" feature=[fm::Feature|QualifiedName] "," "advice" advice=[uml::Model|QualifiedName] ","
		//"pointcuts" "{" pointcuts+=Pointcut ("," pointcuts+=Pointcut)* "}" "," "compositions" "{" compositions+=Composition
		//("," compositions+=Composition)* "}" "}"
		public Group getGroup() { return cGroup; }

		//"aspect"
		public Keyword getAspectKeyword_0() { return cAspectKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"feature"
		public Keyword getFeatureKeyword_3() { return cFeatureKeyword_3; }

		//feature=[fm::Feature|QualifiedName]
		public Assignment getFeatureAssignment_4() { return cFeatureAssignment_4; }

		//[fm::Feature|QualifiedName]
		public CrossReference getFeatureFeatureCrossReference_4_0() { return cFeatureFeatureCrossReference_4_0; }

		//QualifiedName
		public RuleCall getFeatureFeatureQualifiedNameParserRuleCall_4_0_1() { return cFeatureFeatureQualifiedNameParserRuleCall_4_0_1; }

		//","
		public Keyword getCommaKeyword_5() { return cCommaKeyword_5; }

		//"advice"
		public Keyword getAdviceKeyword_6() { return cAdviceKeyword_6; }

		//advice=[uml::Model|QualifiedName]
		public Assignment getAdviceAssignment_7() { return cAdviceAssignment_7; }

		//[uml::Model|QualifiedName]
		public CrossReference getAdviceModelCrossReference_7_0() { return cAdviceModelCrossReference_7_0; }

		//QualifiedName
		public RuleCall getAdviceModelQualifiedNameParserRuleCall_7_0_1() { return cAdviceModelQualifiedNameParserRuleCall_7_0_1; }

		//","
		public Keyword getCommaKeyword_8() { return cCommaKeyword_8; }

		//"pointcuts"
		public Keyword getPointcutsKeyword_9() { return cPointcutsKeyword_9; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_10() { return cLeftCurlyBracketKeyword_10; }

		//pointcuts+=Pointcut
		public Assignment getPointcutsAssignment_11() { return cPointcutsAssignment_11; }

		//Pointcut
		public RuleCall getPointcutsPointcutParserRuleCall_11_0() { return cPointcutsPointcutParserRuleCall_11_0; }

		//("," pointcuts+=Pointcut)*
		public Group getGroup_12() { return cGroup_12; }

		//","
		public Keyword getCommaKeyword_12_0() { return cCommaKeyword_12_0; }

		//pointcuts+=Pointcut
		public Assignment getPointcutsAssignment_12_1() { return cPointcutsAssignment_12_1; }

		//Pointcut
		public RuleCall getPointcutsPointcutParserRuleCall_12_1_0() { return cPointcutsPointcutParserRuleCall_12_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }

		//","
		public Keyword getCommaKeyword_14() { return cCommaKeyword_14; }

		//"compositions"
		public Keyword getCompositionsKeyword_15() { return cCompositionsKeyword_15; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_16() { return cLeftCurlyBracketKeyword_16; }

		//compositions+=Composition
		public Assignment getCompositionsAssignment_17() { return cCompositionsAssignment_17; }

		//Composition
		public RuleCall getCompositionsCompositionParserRuleCall_17_0() { return cCompositionsCompositionParserRuleCall_17_0; }

		//("," compositions+=Composition)*
		public Group getGroup_18() { return cGroup_18; }

		//","
		public Keyword getCommaKeyword_18_0() { return cCommaKeyword_18_0; }

		//compositions+=Composition
		public Assignment getCompositionsAssignment_18_1() { return cCompositionsAssignment_18_1; }

		//Composition
		public RuleCall getCompositionsCompositionParserRuleCall_18_1_0() { return cCompositionsCompositionParserRuleCall_18_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_19() { return cRightCurlyBracketKeyword_19; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_20() { return cRightCurlyBracketKeyword_20; }
	}

	public class PointcutElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "eu.supersede.dynadapt.dsl.Aspect.Pointcut");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPointcutKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cPatternKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cPatternAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cPatternPatternCrossReference_4_0 = (CrossReference)cPatternAssignment_4.eContents().get(0);
		private final RuleCall cPatternPatternQualifiedNameParserRuleCall_4_0_1 = (RuleCall)cPatternPatternCrossReference_4_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCommaKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cRoleKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cRoleAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cRoleStereotypeCrossReference_5_2_0 = (CrossReference)cRoleAssignment_5_2.eContents().get(0);
		private final RuleCall cRoleStereotypeQualifiedNameParserRuleCall_5_2_0_1 = (RuleCall)cRoleStereotypeCrossReference_5_2_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Pointcut:
		//	"pointcut" name=ID "{"
		//	"pattern" pattern=[pattern::Pattern|QualifiedName] ("," "role" role=[uml::Stereotype|QualifiedName])?
		//	"}";
		@Override public ParserRule getRule() { return rule; }

		//"pointcut" name=ID "{" "pattern" pattern=[pattern::Pattern|QualifiedName] ("," "role"
		//role=[uml::Stereotype|QualifiedName])? "}"
		public Group getGroup() { return cGroup; }

		//"pointcut"
		public Keyword getPointcutKeyword_0() { return cPointcutKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"pattern"
		public Keyword getPatternKeyword_3() { return cPatternKeyword_3; }

		//pattern=[pattern::Pattern|QualifiedName]
		public Assignment getPatternAssignment_4() { return cPatternAssignment_4; }

		//[pattern::Pattern|QualifiedName]
		public CrossReference getPatternPatternCrossReference_4_0() { return cPatternPatternCrossReference_4_0; }

		//QualifiedName
		public RuleCall getPatternPatternQualifiedNameParserRuleCall_4_0_1() { return cPatternPatternQualifiedNameParserRuleCall_4_0_1; }

		//("," "role" role=[uml::Stereotype|QualifiedName])?
		public Group getGroup_5() { return cGroup_5; }

		//","
		public Keyword getCommaKeyword_5_0() { return cCommaKeyword_5_0; }

		//"role"
		public Keyword getRoleKeyword_5_1() { return cRoleKeyword_5_1; }

		//role=[uml::Stereotype|QualifiedName]
		public Assignment getRoleAssignment_5_2() { return cRoleAssignment_5_2; }

		//[uml::Stereotype|QualifiedName]
		public CrossReference getRoleStereotypeCrossReference_5_2_0() { return cRoleStereotypeCrossReference_5_2_0; }

		//QualifiedName
		public RuleCall getRoleStereotypeQualifiedNameParserRuleCall_5_2_0_1() { return cRoleStereotypeQualifiedNameParserRuleCall_5_2_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class CompositionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "eu.supersede.dynadapt.dsl.Aspect.Composition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCompositionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cFeature_enabledKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cFeature_enabledAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cFeature_enabledEBOOLEANTerminalRuleCall_4_0 = (RuleCall)cFeature_enabledAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCommaKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cJointpointRoleKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cJointpointRoleAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cJointpointRoleStereotypeCrossReference_5_2_0 = (CrossReference)cJointpointRoleAssignment_5_2.eContents().get(0);
		private final RuleCall cJointpointRoleStereotypeQualifiedNameParserRuleCall_5_2_0_1 = (RuleCall)cJointpointRoleStereotypeCrossReference_5_2_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cCommaKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cAdviceRoleKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cAdviceAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final CrossReference cAdviceStereotypeCrossReference_6_2_0 = (CrossReference)cAdviceAssignment_6_2.eContents().get(0);
		private final RuleCall cAdviceStereotypeQualifiedNameParserRuleCall_6_2_0_1 = (RuleCall)cAdviceStereotypeCrossReference_6_2_0.eContents().get(1);
		private final Keyword cCommaKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cActionKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cActionAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cActionActionParserRuleCall_9_0 = (RuleCall)cActionAssignment_9.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//Composition:
		//	"composition" name=ID "{"
		//	"feature_enabled" feature_enabled=EBOOLEAN ("," "jointpointRole" jointpointRole=[uml::Stereotype|QualifiedName])? (","
		//	"adviceRole" advice=[uml::Stereotype|QualifiedName])?
		//	"," "action" action=Action
		//	"}";
		@Override public ParserRule getRule() { return rule; }

		//"composition" name=ID "{" "feature_enabled" feature_enabled=EBOOLEAN ("," "jointpointRole"
		//jointpointRole=[uml::Stereotype|QualifiedName])? ("," "adviceRole" advice=[uml::Stereotype|QualifiedName])? ","
		//"action" action=Action "}"
		public Group getGroup() { return cGroup; }

		//"composition"
		public Keyword getCompositionKeyword_0() { return cCompositionKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"feature_enabled"
		public Keyword getFeature_enabledKeyword_3() { return cFeature_enabledKeyword_3; }

		//feature_enabled=EBOOLEAN
		public Assignment getFeature_enabledAssignment_4() { return cFeature_enabledAssignment_4; }

		//EBOOLEAN
		public RuleCall getFeature_enabledEBOOLEANTerminalRuleCall_4_0() { return cFeature_enabledEBOOLEANTerminalRuleCall_4_0; }

		//("," "jointpointRole" jointpointRole=[uml::Stereotype|QualifiedName])?
		public Group getGroup_5() { return cGroup_5; }

		//","
		public Keyword getCommaKeyword_5_0() { return cCommaKeyword_5_0; }

		//"jointpointRole"
		public Keyword getJointpointRoleKeyword_5_1() { return cJointpointRoleKeyword_5_1; }

		//jointpointRole=[uml::Stereotype|QualifiedName]
		public Assignment getJointpointRoleAssignment_5_2() { return cJointpointRoleAssignment_5_2; }

		//[uml::Stereotype|QualifiedName]
		public CrossReference getJointpointRoleStereotypeCrossReference_5_2_0() { return cJointpointRoleStereotypeCrossReference_5_2_0; }

		//QualifiedName
		public RuleCall getJointpointRoleStereotypeQualifiedNameParserRuleCall_5_2_0_1() { return cJointpointRoleStereotypeQualifiedNameParserRuleCall_5_2_0_1; }

		//("," "adviceRole" advice=[uml::Stereotype|QualifiedName])?
		public Group getGroup_6() { return cGroup_6; }

		//","
		public Keyword getCommaKeyword_6_0() { return cCommaKeyword_6_0; }

		//"adviceRole"
		public Keyword getAdviceRoleKeyword_6_1() { return cAdviceRoleKeyword_6_1; }

		//advice=[uml::Stereotype|QualifiedName]
		public Assignment getAdviceAssignment_6_2() { return cAdviceAssignment_6_2; }

		//[uml::Stereotype|QualifiedName]
		public CrossReference getAdviceStereotypeCrossReference_6_2_0() { return cAdviceStereotypeCrossReference_6_2_0; }

		//QualifiedName
		public RuleCall getAdviceStereotypeQualifiedNameParserRuleCall_6_2_0_1() { return cAdviceStereotypeQualifiedNameParserRuleCall_6_2_0_1; }

		//","
		public Keyword getCommaKeyword_7() { return cCommaKeyword_7; }

		//"action"
		public Keyword getActionKeyword_8() { return cActionKeyword_8; }

		//action=Action
		public Assignment getActionAssignment_9() { return cActionAssignment_9; }

		//Action
		public RuleCall getActionActionParserRuleCall_9_0() { return cActionActionParserRuleCall_9_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}

	public class ActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "eu.supersede.dynadapt.dsl.Aspect.Action");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cAddKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cDeleteKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cReplaceKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		private final Keyword cAssociateKeyword_3 = (Keyword)cAlternatives.eContents().get(3);
		
		//Action:
		//	'add' | 'delete' | 'replace' | 'associate';
		@Override public ParserRule getRule() { return rule; }

		//'add' | 'delete' | 'replace' | 'associate'
		public Alternatives getAlternatives() { return cAlternatives; }

		//'add'
		public Keyword getAddKeyword_0() { return cAddKeyword_0; }

		//'delete'
		public Keyword getDeleteKeyword_1() { return cDeleteKeyword_1; }

		//'replace'
		public Keyword getReplaceKeyword_2() { return cReplaceKeyword_2; }

		//'associate'
		public Keyword getAssociateKeyword_3() { return cAssociateKeyword_3; }
	}

	public class QualifiedNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "eu.supersede.dynadapt.dsl.Aspect.QualifiedName");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//QualifiedName:
		//	ID (=> '.' ID)*;
		@Override public ParserRule getRule() { return rule; }

		//ID (=> '.' ID)*
		public Group getGroup() { return cGroup; }

		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }

		//(=> '.' ID)*
		public Group getGroup_1() { return cGroup_1; }

		//=> '.'
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }
	}
	
	
	private final AspectElements pAspect;
	private final PointcutElements pPointcut;
	private final CompositionElements pComposition;
	private final ActionElements pAction;
	private final QualifiedNameElements pQualifiedName;
	private final TerminalRule tEBOOLEAN;
	
	private final Grammar grammar;

	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public AspectGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pAspect = new AspectElements();
		this.pPointcut = new PointcutElements();
		this.pComposition = new CompositionElements();
		this.pAction = new ActionElements();
		this.pQualifiedName = new QualifiedNameElements();
		this.tEBOOLEAN = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "eu.supersede.dynadapt.dsl.Aspect.EBOOLEAN");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("eu.supersede.dynadapt.dsl.Aspect".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Aspect:
	//	"aspect" name=ID "{"
	//	"feature" feature=[fm::Feature|QualifiedName]
	//	"," "advice" advice=[uml::Model|QualifiedName]
	//	"," "pointcuts" "{" pointcuts+=Pointcut ("," pointcuts+=Pointcut)* "}"
	//	"," "compositions" "{" compositions+=Composition ("," compositions+=Composition)* "}"
	//	"}";
	public AspectElements getAspectAccess() {
		return pAspect;
	}
	
	public ParserRule getAspectRule() {
		return getAspectAccess().getRule();
	}

	//Pointcut:
	//	"pointcut" name=ID "{"
	//	"pattern" pattern=[pattern::Pattern|QualifiedName] ("," "role" role=[uml::Stereotype|QualifiedName])?
	//	"}";
	public PointcutElements getPointcutAccess() {
		return pPointcut;
	}
	
	public ParserRule getPointcutRule() {
		return getPointcutAccess().getRule();
	}

	//Composition:
	//	"composition" name=ID "{"
	//	"feature_enabled" feature_enabled=EBOOLEAN ("," "jointpointRole" jointpointRole=[uml::Stereotype|QualifiedName])? (","
	//	"adviceRole" advice=[uml::Stereotype|QualifiedName])?
	//	"," "action" action=Action
	//	"}";
	public CompositionElements getCompositionAccess() {
		return pComposition;
	}
	
	public ParserRule getCompositionRule() {
		return getCompositionAccess().getRule();
	}

	//Action:
	//	'add' | 'delete' | 'replace' | 'associate';
	public ActionElements getActionAccess() {
		return pAction;
	}
	
	public ParserRule getActionRule() {
		return getActionAccess().getRule();
	}

	//QualifiedName:
	//	ID (=> '.' ID)*;
	public QualifiedNameElements getQualifiedNameAccess() {
		return pQualifiedName;
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}

	//terminal EBOOLEAN returns ecore::EBooleanObject:
	//	'true' | 'false';
	public TerminalRule getEBOOLEANRule() {
		return tEBOOLEAN;
	} 

	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	'/ *'->'* /';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
