/*
* generated by Xtext
*/
package cz.zcu.yafmt.clang.bcl.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class BooleanConstraintLanguageGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Expression");
		private final RuleCall cContextualExpressionParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Expression:
		//	ContextualExpression;
		public ParserRule getRule() { return rule; }

		//ContextualExpression
		public RuleCall getContextualExpressionParserRuleCall() { return cContextualExpressionParserRuleCall; }
	}

	public class ContextualExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ContextualExpression");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cForallKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Action cForAllContextualExpressionAction_0_1 = (Action)cGroup_0.eContents().get(1);
		private final Assignment cContextIdAssignment_0_2 = (Assignment)cGroup_0.eContents().get(2);
		private final RuleCall cContextIdIDTerminalRuleCall_0_2_0 = (RuleCall)cContextIdAssignment_0_2.eContents().get(0);
		private final Keyword cColonKeyword_0_3 = (Keyword)cGroup_0.eContents().get(3);
		private final Assignment cExpressionAssignment_0_4 = (Assignment)cGroup_0.eContents().get(4);
		private final RuleCall cExpressionEquationParserRuleCall_0_4_0 = (RuleCall)cExpressionAssignment_0_4.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cExistsKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Action cExistsContextualExpressionAction_1_1 = (Action)cGroup_1.eContents().get(1);
		private final Assignment cContextIdAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cContextIdIDTerminalRuleCall_1_2_0 = (RuleCall)cContextIdAssignment_1_2.eContents().get(0);
		private final Keyword cColonKeyword_1_3 = (Keyword)cGroup_1.eContents().get(3);
		private final Assignment cExpressionAssignment_1_4 = (Assignment)cGroup_1.eContents().get(4);
		private final RuleCall cExpressionEquationParserRuleCall_1_4_0 = (RuleCall)cExpressionAssignment_1_4.eContents().get(0);
		private final RuleCall cEquationParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//ContextualExpression returns Expression:
		//	"forall" {ForAllContextualExpression} contextId=ID ":" expression=Equation | "exists" {ExistsContextualExpression}
		//	contextId=ID ":" expression=Equation | Equation;
		public ParserRule getRule() { return rule; }

		//"forall" {ForAllContextualExpression} contextId=ID ":" expression=Equation | "exists" {ExistsContextualExpression}
		//contextId=ID ":" expression=Equation | Equation
		public Alternatives getAlternatives() { return cAlternatives; }

		//"forall" {ForAllContextualExpression} contextId=ID ":" expression=Equation
		public Group getGroup_0() { return cGroup_0; }

		//"forall"
		public Keyword getForallKeyword_0_0() { return cForallKeyword_0_0; }

		//{ForAllContextualExpression}
		public Action getForAllContextualExpressionAction_0_1() { return cForAllContextualExpressionAction_0_1; }

		//contextId=ID
		public Assignment getContextIdAssignment_0_2() { return cContextIdAssignment_0_2; }

		//ID
		public RuleCall getContextIdIDTerminalRuleCall_0_2_0() { return cContextIdIDTerminalRuleCall_0_2_0; }

		//":"
		public Keyword getColonKeyword_0_3() { return cColonKeyword_0_3; }

		//expression=Equation
		public Assignment getExpressionAssignment_0_4() { return cExpressionAssignment_0_4; }

		//Equation
		public RuleCall getExpressionEquationParserRuleCall_0_4_0() { return cExpressionEquationParserRuleCall_0_4_0; }

		//"exists" {ExistsContextualExpression} contextId=ID ":" expression=Equation
		public Group getGroup_1() { return cGroup_1; }

		//"exists"
		public Keyword getExistsKeyword_1_0() { return cExistsKeyword_1_0; }

		//{ExistsContextualExpression}
		public Action getExistsContextualExpressionAction_1_1() { return cExistsContextualExpressionAction_1_1; }

		//contextId=ID
		public Assignment getContextIdAssignment_1_2() { return cContextIdAssignment_1_2; }

		//ID
		public RuleCall getContextIdIDTerminalRuleCall_1_2_0() { return cContextIdIDTerminalRuleCall_1_2_0; }

		//":"
		public Keyword getColonKeyword_1_3() { return cColonKeyword_1_3; }

		//expression=Equation
		public Assignment getExpressionAssignment_1_4() { return cExpressionAssignment_1_4; }

		//Equation
		public RuleCall getExpressionEquationParserRuleCall_1_4_0() { return cExpressionEquationParserRuleCall_1_4_0; }

		//Equation
		public RuleCall getEquationParserRuleCall_2() { return cEquationParserRuleCall_2; }
	}

	public class EquationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Equation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cImplicationParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cEquationLeftPartAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cEqualsKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cRightPartAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightPartImplicationParserRuleCall_1_2_0 = (RuleCall)cRightPartAssignment_1_2.eContents().get(0);
		
		//Equation returns Expression:
		//	Implication ({Equation.leftPart=current} "equals" rightPart=Implication)*;
		public ParserRule getRule() { return rule; }

		//Implication ({Equation.leftPart=current} "equals" rightPart=Implication)*
		public Group getGroup() { return cGroup; }

		//Implication
		public RuleCall getImplicationParserRuleCall_0() { return cImplicationParserRuleCall_0; }

		//({Equation.leftPart=current} "equals" rightPart=Implication)*
		public Group getGroup_1() { return cGroup_1; }

		//{Equation.leftPart=current}
		public Action getEquationLeftPartAction_1_0() { return cEquationLeftPartAction_1_0; }

		//"equals"
		public Keyword getEqualsKeyword_1_1() { return cEqualsKeyword_1_1; }

		//rightPart=Implication
		public Assignment getRightPartAssignment_1_2() { return cRightPartAssignment_1_2; }

		//Implication
		public RuleCall getRightPartImplicationParserRuleCall_1_2_0() { return cRightPartImplicationParserRuleCall_1_2_0; }
	}

	public class ImplicationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Implication");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cDisjunctionParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cImplicationLeftPartAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cImpliesKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cRightPartAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightPartDisjunctionParserRuleCall_1_2_0 = (RuleCall)cRightPartAssignment_1_2.eContents().get(0);
		
		//Implication returns Expression:
		//	Disjunction ({Implication.leftPart=current} "implies" rightPart=Disjunction)*;
		public ParserRule getRule() { return rule; }

		//Disjunction ({Implication.leftPart=current} "implies" rightPart=Disjunction)*
		public Group getGroup() { return cGroup; }

		//Disjunction
		public RuleCall getDisjunctionParserRuleCall_0() { return cDisjunctionParserRuleCall_0; }

		//({Implication.leftPart=current} "implies" rightPart=Disjunction)*
		public Group getGroup_1() { return cGroup_1; }

		//{Implication.leftPart=current}
		public Action getImplicationLeftPartAction_1_0() { return cImplicationLeftPartAction_1_0; }

		//"implies"
		public Keyword getImpliesKeyword_1_1() { return cImpliesKeyword_1_1; }

		//rightPart=Disjunction
		public Assignment getRightPartAssignment_1_2() { return cRightPartAssignment_1_2; }

		//Disjunction
		public RuleCall getRightPartDisjunctionParserRuleCall_1_2_0() { return cRightPartDisjunctionParserRuleCall_1_2_0; }
	}

	public class DisjunctionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Disjunction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cConjunctionParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cDisjunctionLeftPartAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cOrKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cRightPartAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightPartConjunctionParserRuleCall_1_2_0 = (RuleCall)cRightPartAssignment_1_2.eContents().get(0);
		
		//Disjunction returns Expression:
		//	Conjunction ({Disjunction.leftPart=current} "or" rightPart=Conjunction)*;
		public ParserRule getRule() { return rule; }

		//Conjunction ({Disjunction.leftPart=current} "or" rightPart=Conjunction)*
		public Group getGroup() { return cGroup; }

		//Conjunction
		public RuleCall getConjunctionParserRuleCall_0() { return cConjunctionParserRuleCall_0; }

		//({Disjunction.leftPart=current} "or" rightPart=Conjunction)*
		public Group getGroup_1() { return cGroup_1; }

		//{Disjunction.leftPart=current}
		public Action getDisjunctionLeftPartAction_1_0() { return cDisjunctionLeftPartAction_1_0; }

		//"or"
		public Keyword getOrKeyword_1_1() { return cOrKeyword_1_1; }

		//rightPart=Conjunction
		public Assignment getRightPartAssignment_1_2() { return cRightPartAssignment_1_2; }

		//Conjunction
		public RuleCall getRightPartConjunctionParserRuleCall_1_2_0() { return cRightPartConjunctionParserRuleCall_1_2_0; }
	}

	public class ConjunctionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Conjunction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cNegationParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cConjunctionLeftPartAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cAndKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cRightPartAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightPartNegationParserRuleCall_1_2_0 = (RuleCall)cRightPartAssignment_1_2.eContents().get(0);
		
		//Conjunction returns Expression:
		//	Negation ({Conjunction.leftPart=current} "and" rightPart=Negation)*;
		public ParserRule getRule() { return rule; }

		//Negation ({Conjunction.leftPart=current} "and" rightPart=Negation)*
		public Group getGroup() { return cGroup; }

		//Negation
		public RuleCall getNegationParserRuleCall_0() { return cNegationParserRuleCall_0; }

		//({Conjunction.leftPart=current} "and" rightPart=Negation)*
		public Group getGroup_1() { return cGroup_1; }

		//{Conjunction.leftPart=current}
		public Action getConjunctionLeftPartAction_1_0() { return cConjunctionLeftPartAction_1_0; }

		//"and"
		public Keyword getAndKeyword_1_1() { return cAndKeyword_1_1; }

		//rightPart=Negation
		public Assignment getRightPartAssignment_1_2() { return cRightPartAssignment_1_2; }

		//Negation
		public RuleCall getRightPartNegationParserRuleCall_1_2_0() { return cRightPartNegationParserRuleCall_1_2_0; }
	}

	public class NegationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Negation");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cPrimaryExpressionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cNotKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Action cNegationAction_1_1 = (Action)cGroup_1.eContents().get(1);
		private final Assignment cExpressionAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cExpressionPrimaryExpressionParserRuleCall_1_2_0 = (RuleCall)cExpressionAssignment_1_2.eContents().get(0);
		
		//Negation returns Expression:
		//	PrimaryExpression | "not" {Negation} expression=PrimaryExpression;
		public ParserRule getRule() { return rule; }

		//PrimaryExpression | "not" {Negation} expression=PrimaryExpression
		public Alternatives getAlternatives() { return cAlternatives; }

		//PrimaryExpression
		public RuleCall getPrimaryExpressionParserRuleCall_0() { return cPrimaryExpressionParserRuleCall_0; }

		//"not" {Negation} expression=PrimaryExpression
		public Group getGroup_1() { return cGroup_1; }

		//"not"
		public Keyword getNotKeyword_1_0() { return cNotKeyword_1_0; }

		//{Negation}
		public Action getNegationAction_1_1() { return cNegationAction_1_1; }

		//expression=PrimaryExpression
		public Assignment getExpressionAssignment_1_2() { return cExpressionAssignment_1_2; }

		//PrimaryExpression
		public RuleCall getExpressionPrimaryExpressionParserRuleCall_1_2_0() { return cExpressionPrimaryExpressionParserRuleCall_1_2_0; }
	}

	public class PrimaryExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "PrimaryExpression");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cPrimaryExpressionAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Assignment cFeatureIdAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cFeatureIdIDTerminalRuleCall_0_1_0 = (RuleCall)cFeatureIdAssignment_0_1.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cExpressionParserRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		
		//PrimaryExpression returns Expression:
		//	{PrimaryExpression} featureId=ID | "(" Expression ")";
		public ParserRule getRule() { return rule; }

		//{PrimaryExpression} featureId=ID | "(" Expression ")"
		public Alternatives getAlternatives() { return cAlternatives; }

		//{PrimaryExpression} featureId=ID
		public Group getGroup_0() { return cGroup_0; }

		//{PrimaryExpression}
		public Action getPrimaryExpressionAction_0_0() { return cPrimaryExpressionAction_0_0; }

		//featureId=ID
		public Assignment getFeatureIdAssignment_0_1() { return cFeatureIdAssignment_0_1; }

		//ID
		public RuleCall getFeatureIdIDTerminalRuleCall_0_1_0() { return cFeatureIdIDTerminalRuleCall_0_1_0; }

		//"(" Expression ")"
		public Group getGroup_1() { return cGroup_1; }

		//"("
		public Keyword getLeftParenthesisKeyword_1_0() { return cLeftParenthesisKeyword_1_0; }

		//Expression
		public RuleCall getExpressionParserRuleCall_1_1() { return cExpressionParserRuleCall_1_1; }

		//")"
		public Keyword getRightParenthesisKeyword_1_2() { return cRightParenthesisKeyword_1_2; }
	}
	
	
	private ExpressionElements pExpression;
	private ContextualExpressionElements pContextualExpression;
	private EquationElements pEquation;
	private ImplicationElements pImplication;
	private DisjunctionElements pDisjunction;
	private ConjunctionElements pConjunction;
	private NegationElements pNegation;
	private PrimaryExpressionElements pPrimaryExpression;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public BooleanConstraintLanguageGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("cz.zcu.yafmt.clang.bcl.BooleanConstraintLanguage".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Expression:
	//	ContextualExpression;
	public ExpressionElements getExpressionAccess() {
		return (pExpression != null) ? pExpression : (pExpression = new ExpressionElements());
	}
	
	public ParserRule getExpressionRule() {
		return getExpressionAccess().getRule();
	}

	//ContextualExpression returns Expression:
	//	"forall" {ForAllContextualExpression} contextId=ID ":" expression=Equation | "exists" {ExistsContextualExpression}
	//	contextId=ID ":" expression=Equation | Equation;
	public ContextualExpressionElements getContextualExpressionAccess() {
		return (pContextualExpression != null) ? pContextualExpression : (pContextualExpression = new ContextualExpressionElements());
	}
	
	public ParserRule getContextualExpressionRule() {
		return getContextualExpressionAccess().getRule();
	}

	//Equation returns Expression:
	//	Implication ({Equation.leftPart=current} "equals" rightPart=Implication)*;
	public EquationElements getEquationAccess() {
		return (pEquation != null) ? pEquation : (pEquation = new EquationElements());
	}
	
	public ParserRule getEquationRule() {
		return getEquationAccess().getRule();
	}

	//Implication returns Expression:
	//	Disjunction ({Implication.leftPart=current} "implies" rightPart=Disjunction)*;
	public ImplicationElements getImplicationAccess() {
		return (pImplication != null) ? pImplication : (pImplication = new ImplicationElements());
	}
	
	public ParserRule getImplicationRule() {
		return getImplicationAccess().getRule();
	}

	//Disjunction returns Expression:
	//	Conjunction ({Disjunction.leftPart=current} "or" rightPart=Conjunction)*;
	public DisjunctionElements getDisjunctionAccess() {
		return (pDisjunction != null) ? pDisjunction : (pDisjunction = new DisjunctionElements());
	}
	
	public ParserRule getDisjunctionRule() {
		return getDisjunctionAccess().getRule();
	}

	//Conjunction returns Expression:
	//	Negation ({Conjunction.leftPart=current} "and" rightPart=Negation)*;
	public ConjunctionElements getConjunctionAccess() {
		return (pConjunction != null) ? pConjunction : (pConjunction = new ConjunctionElements());
	}
	
	public ParserRule getConjunctionRule() {
		return getConjunctionAccess().getRule();
	}

	//Negation returns Expression:
	//	PrimaryExpression | "not" {Negation} expression=PrimaryExpression;
	public NegationElements getNegationAccess() {
		return (pNegation != null) ? pNegation : (pNegation = new NegationElements());
	}
	
	public ParserRule getNegationRule() {
		return getNegationAccess().getRule();
	}

	//PrimaryExpression returns Expression:
	//	{PrimaryExpression} featureId=ID | "(" Expression ")";
	public PrimaryExpressionElements getPrimaryExpressionAccess() {
		return (pPrimaryExpression != null) ? pPrimaryExpression : (pPrimaryExpression = new PrimaryExpressionElements());
	}
	
	public ParserRule getPrimaryExpressionRule() {
		return getPrimaryExpressionAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
