# $Id: makefile 73647 2015-10-09 23:22:05Z cxh $
# The name of the FMU to be built.
FMU_NAME = tankOpen

# Need sqrt()
USERLIBS = -lm

# The rules are in a separate file so that we can easily update them.
include fmu.mk
